[package]
name = "project-name"
version = "0.1.0"
authors = ["OffTheHeezay <den_9912@mail.ru>"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
creator = "0.4.1"
bevy = { git = "https://github.com/creator-rs/bevy.git", rev = "3ebf26249b698c8379443f73a1cbeb57779e3e6d" }

[package.metadata]
app_name = "project-name"
icon = "ic_launcher"
target_sdk_version = 30

android_assets = "assets"
android_res = "res/android"

apple_assets = "assets"
apple_res = "res/apple"
